# (documento 1 - default)
spring:
  application:
    name: portfolio
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Sao_Paulo

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:portfolio}
    username: ${POSTGRES_USER:portfolio}
    password: ${POSTGRES_PASSWORD:portfolio}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: America/Sao_Paulo
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

management:
  endpoints:
    web.exposure.include: health,info,metrics
  endpoint.health.show-details: never

server:
  port: 8080

app:
  members:
    base-url: ${MEMBERS_API_BASE_URL:http://localhost:8081}

---
# (documento 2 - profile docker)
spring:
  config:
    activate:
      on-profile: docker

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB:portfolio}
    username: ${POSTGRES_USER:portfolio}
    password: ${POSTGRES_PASSWORD:portfolio}

app:
  members:
    base-url: ${MEMBERS_API_BASE_URL:http://wiremock:8080}
